## Artificial Neural Network

In [1]:
#Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.12.0'

### Part 1 - Data preprocessing

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [3]:
#Encoding categorical data
#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
#One hot encoding the "geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(y)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [4]:
#Splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2,
                                                    random_state=0) 

In [5]:
#Featurinf scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Part 2 - Builing the ANN

In [6]:
#Iniatializing the ANN
ann = tf.keras.models.Sequential()

In [7]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [8]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [9]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Part 3 - Training the ANN

In [10]:
# Compiling the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [11]:
# Training ANN on the training set
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 771us/step - loss: 0.7572 - accuracy: 0.4724
Epoch 2/100
250/250 [==============================] - 0s 745us/step - loss: 0.5957 - accuracy: 0.7897
Epoch 3/100
250/250 [==============================] - 0s 755us/step - loss: 0.5021 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 0s 772us/step - loss: 0.4527 - accuracy: 0.8006
Epoch 5/100
250/250 [==============================] - 0s 729us/step - loss: 0.4324 - accuracy: 0.8096
Epoch 6/100
250/250 [==============================] - 0s 806us/step - loss: 0.4222 - accuracy: 0.8136
Epoch 7/100
250/250 [==============================] - 0s 737us/step - loss: 0.4164 - accuracy: 0.8154
Epoch 8/100
250/250 [==============================] - 0s 709us/step - loss: 0.4124 - accuracy: 0.8189
Epoch 9/100
250/250 [==============================] - 0s 733us/step - loss: 0.4094 - accuracy: 0.8195
Epoch 10/100
250/250 [==============================] - 0s 721us/step - l

### Part 4 - Making the predictions and evaluating the model

In [12]:
#Predicting the result of a single observation
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))> 0.5)

1/1 [==============================] - 0s 112ms/step
[[False]]


In [13]:
# Predicting the test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),
                      y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 579us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [14]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1521   74]
 [ 204  201]]


0.861